const i18Obj = {
  en: {
    skills: "Skills",
    portfolio: "Portfolio",
    video: "Video",
    price: "Price",
    contacts: "Contacts",
    "hero-title": "Alexa Rise",
    "hero-text":
      "Save sincere emotions, romantic feelings and happy moments of life together with professional photographer Alexa Rise",
    hire: "Hire me",
    "skill-title-1": "Digital photography",
    "skill-text-1": "High-quality photos in the studio and on the nature",
    "skill-title-2": "Video shooting",
    "skill-text-2": "Capture your moments so that they always stay with you",
    "skill-title-3": "Rotouch",
    "skill-text-3": "I strive to make photography surpass reality",
    "skill-title-4": "Audio",
    "skill-text-4":
      "Professional sounds recording for video, advertising, portfolio",
    winter: "Winter",
    spring: "Spring",
    summer: "Summer",
    autumn: "Autumn",
    "price-1-1": "One location",
    "price-1-2": "120 photos in color",
    "price-1-3": "12 photos in retouch",
    "price-1-4": "Readiness 2-3 weeks",
    "price-1-5": "Make up, visage",
    "price-2-1": "One or two locations",
    "price-2-2": "200 photos in color",
    "price-2-3": "20 photos in retouch",
    "price-2-4": "Readiness 1-2 weeks",
    "price-2-5": "Make up, visage",
    "price-3-1": "Three locations or more",
    "price-3-2": "300 photos in color",
    "price-3-3": "50 photos in retouch",
    "price-3-4": "Readiness 1 week",
    "price-3-5": "Make up, visage, hairstyle",
    order: "Order shooting",
    "contact-me": "Contact me",
    "send-message": "Send message",
    "E-mail": "E-mail",
    Phone: "Phone",
    Message: "Message",
  },
  ru: {
    skills: "Навыки",
    portfolio: "Портфолио",
    video: "Видео",
    price: "Цены",
    contacts: "Контакты",
    "hero-title": "Алекса Райс",
    "hero-text":
      "Сохраните искренние эмоции, романтические переживания и счастливые моменты жизни вместе с профессиональным фотографом",
    hire: "Пригласить",
    "skill-title-1": "Фотография",
    "skill-text-1": "Высококачественные фото в студии и на природе",
    "skill-title-2": "Видеосъемка",
    "skill-text-2":
      "Запечатлите лучшие моменты, чтобы они всегда оставались с вами",
    "skill-title-3": "Ретушь",
    "skill-text-3":
      "Я стремлюсь к тому, чтобы фотография превосходила реальность",
    "skill-title-4": "Звук",
    "skill-text-4":
      "Профессиональная запись звука для видео, рекламы, портфолио",
    winter: "Зима",
    spring: "Весна",
    summer: "Лето",
    autumn: "Осень",
    "price-1-1": "Одна локация",
    "price-1-2": "120 цветных фото",
    "price-1-3": "12 отретушированных фото",
    "price-1-4": "Готовность через 2-3 недели",
    "price-1-5": "Макияж, визаж",
    "price-2-1": "Одна-две локации",
    "price-2-2": "200 цветных фото",
    "price-2-3": "20 отретушированных фото",
    "price-2-4": "Готовность через 1-2 недели",
    "price-2-5": "Макияж, визаж",
    "price-3-1": "Три локации и больше",
    "price-3-2": "300 цветных фото",
    "price-3-3": "50 отретушированных фото",
    "price-3-4": "Готовность через 1 неделю",
    "price-3-5": "Макияж, визаж, прическа",
    order: "Заказать съемку",
    "contact-me": "Свяжитесь со мной",
    "send-message": "Отправить",
    "E-mail": "Почта",
    Phone: "Телефон",
    Message: "Сообщение",
  },
};
export default i18Obj;
